#
#  Makefile
#  	Apple //GS Build Engine for ORCA and Merlin
#

all:
	make -f shell.mk
	make -f babelfish.mk
	
clean:
	make -f shell.mk clean
	make -f babelfish.mk clean
	
execute:
	make -f shell.mk execute
